stages:
  - build
  - test
  - release

default:
  before_script:
    # move this repo to src of catkin workspace, .catkin_tools, build and devel spaces are passed as artifacts - do not move!
    - mkdir src
    - ls --almost-all --ignore .catkin_tools --ignore build --ignore devel --ignore src | xargs mv -t src
    # setup the workspace as ROS Devcontainer
    - git clone --depth 1 https://gitlab-ci-token:${CI_JOB_TOKEN}@git-ce.rwth-aachen.de/g-med-irt-robotik/ros-devcontainer.git /ros_devcontainer
    - cd /ros_devcontainer && ls --almost-all | xargs mv -n -t ${CI_PROJECT_DIR} && cd ${CI_PROJECT_DIR}
    # configure gitlab token before cloning dependencies
    - sed -i 's/https:\/\/git-ce\./https:\/\/gitlab-ci-token:\$\{CI_JOB_TOKEN\}\@git-ce\./g' src/.rosinstall
    - wstool update -t src
    # load remaining dependencies and setup catkin config
    - . .devcontainer/postCreate.sh

  cache:
    # Good practice
    key: ${CI_COMMIT_REF_SLUG}
    # Caching might improve CI speed
    paths:
      - .catkin_tools
      - build
      - devel
  image: $CI_REGISTRY/g-med-irt-robotik/ros-devcontainer/master:noetic-moveit

catkin_tools_build:
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .catkin_tools
      - build
      - devel

catkin_lint:
  stage: test
  script:
    - source devel/setup.bash
    - catkin_lint -W2 --pkg lbrmed_bringup --pkg lbrmed_control --pkg lbrmed_description --pkg lbrmed_hw_fri --pkg lbrmed_moveit_config --pkg lbrmed_msgs

catkin_tools_run_tests:
  stage: test
  script:
    - source devel/setup.bash
    - catkin test --no-deps lbrmed_bringup lbrmed_control lbrmed_description lbrmed_hw_fri lbrmed_moveit_config lbrmed_msgs
