# @license BSD-3 https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2024, Institute of Automatic Control - RWTH Aachen University
# All rights reserved.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  industrial_ci:
    name: ROS Industrial CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "ros-industrial/industrial_ci@master"
        env:
          ROS_DISTRO: noetic
          CATKIN_LINT: true
          CATKIN_LINT_ARGS: -W2
          UPSTREAM_WORKSPACE: .rosinstall
