# @license BSD-3 https://opensource.org/licenses/BSD-3-Clause
# Copyright (c) 2024, Institute of Automatic Control - RWTH Aachen University
# All rights reserved.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # clone target repository
      - uses: "ros-industrial/industrial_ci@master" # run industrial_ci
        env:
          ROS_DISTRO: noetic
          CATKIN_LINT: pedantic
